# Generated by Django 5.0.4 on 2024-05-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rini'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rini',
        ),
        migrations.DeleteModel(
            name='Sear',
        ),
    ]
