# Generated by Django 5.0.4 on 2024-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_rini_delete_sear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=5000)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=50)),
                ('responsetype', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('responsetext', models.CharField(max_length=5000)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
