# Generated by Django 5.0.4 on 2024-05-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_enquiry_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
